language: php
php:
  - nightly
  - 7.2
  - 7.1
  - 7.0

before_install: composer validate --strict

install: composer install

script: composer test

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/composer
